vcom -93 -work ./work ../src/risc_package.vhd
vcom -93 -work ./work ../src/AddSum.vhd
vcom -93 -work ./work ../src/ALU.vhd
vcom -93 -work ./work ../src/ALU_control.vhd
vcom -93 -work ./work ../src/AND_Gate.vhd
vcom -93 -work ./work ../src/OR_Gate.vhd
vcom -93 -work ./work ../src/CU.vhd
vcom -93 -work ./work ../src/forwarding_unit.vhd;
vcom -93 -work ./work ../src/HDU.vhd
vcom -93 -work ./work ../src/imm_gen.vhd
vcom -93 -work ./work ../src/instruction_memory.vhd
vcom -93 -work ./work ../src/mux_ID.vhd
vcom -93 -work ./work ../src/mux21.vhd
vcom -93 -work ./work ../src/mux31.vhd
vcom -93 -work ./work ../src/PC.vhd
vcom -93 -work ./work ../src/PC_instr_mem.vhd
vcom -93 -work ./work ../src/reg.vhd
vcom -93 -work ./work ../src/reg_zero.vhd
vcom -93 -work ./work ../src/reg_NOP.vhd
vcom -93 -work ./work ../src/reg_jal_PC_IF_ID.vhd
vcom -93 -work ./work ../src/register_file.vhd

vcom -93 -work ./work ../src/EX_stage.vhd
vcom -93 -work ./work ../src/ID_stage.vhd
vcom -93 -work ./work ../src/IF_stage.vhd
vcom -93 -work ./work ../src/MEM_stage.vhd
vcom -93 -work ./work ../src/WB_stage.vhd

vcom -93 -work ./work ../src/RISCV.vhd